// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: worldcup.proto

package worldcuppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Equipos aceptados en las predicciones.
type Teams int32

const (
	Teams_TEAMS_UNKNOWN Teams = 0
	Teams_GTM           Teams = 1
	Teams_MEX           Teams = 2
	Teams_BRA           Teams = 3
	Teams_ARG           Teams = 4
	Teams_ESP           Teams = 5
)

// Enum value maps for Teams.
var (
	Teams_name = map[int32]string{
		0: "TEAMS_UNKNOWN",
		1: "GTM",
		2: "MEX",
		3: "BRA",
		4: "ARG",
		5: "ESP",
	}
	Teams_value = map[string]int32{
		"TEAMS_UNKNOWN": 0,
		"GTM":           1,
		"MEX":           2,
		"BRA":           3,
		"ARG":           4,
		"ESP":           5,
	}
)

func (x Teams) Enum() *Teams {
	p := new(Teams)
	*p = x
	return p
}

func (x Teams) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Teams) Descriptor() protoreflect.EnumDescriptor {
	return file_worldcup_proto_enumTypes[0].Descriptor()
}

func (Teams) Type() protoreflect.EnumType {
	return &file_worldcup_proto_enumTypes[0]
}

func (x Teams) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Teams.Descriptor instead.
func (Teams) EnumDescriptor() ([]byte, []int) {
	return file_worldcup_proto_rawDescGZIP(), []int{0}
}

// Predicción enviada desde el cliente al servidor gRPC.
type MatchPredictionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HomeTeam      Teams                  `protobuf:"varint,1,opt,name=home_team,json=homeTeam,proto3,enum=worldcup2026.Teams" json:"home_team,omitempty"`
	AwayTeam      Teams                  `protobuf:"varint,2,opt,name=away_team,json=awayTeam,proto3,enum=worldcup2026.Teams" json:"away_team,omitempty"`
	HomeGoals     int32                  `protobuf:"varint,3,opt,name=home_goals,json=homeGoals,proto3" json:"home_goals,omitempty"`
	AwayGoals     int32                  `protobuf:"varint,4,opt,name=away_goals,json=awayGoals,proto3" json:"away_goals,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchPredictionRequest) Reset() {
	*x = MatchPredictionRequest{}
	mi := &file_worldcup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchPredictionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchPredictionRequest) ProtoMessage() {}

func (x *MatchPredictionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worldcup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchPredictionRequest.ProtoReflect.Descriptor instead.
func (*MatchPredictionRequest) Descriptor() ([]byte, []int) {
	return file_worldcup_proto_rawDescGZIP(), []int{0}
}

func (x *MatchPredictionRequest) GetHomeTeam() Teams {
	if x != nil {
		return x.HomeTeam
	}
	return Teams_TEAMS_UNKNOWN
}

func (x *MatchPredictionRequest) GetAwayTeam() Teams {
	if x != nil {
		return x.AwayTeam
	}
	return Teams_TEAMS_UNKNOWN
}

func (x *MatchPredictionRequest) GetHomeGoals() int32 {
	if x != nil {
		return x.HomeGoals
	}
	return 0
}

func (x *MatchPredictionRequest) GetAwayGoals() int32 {
	if x != nil {
		return x.AwayGoals
	}
	return 0
}

func (x *MatchPredictionRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *MatchPredictionRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// Respuesta enviada por el servidor gRPC.
type MatchPredictionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchPredictionResponse) Reset() {
	*x = MatchPredictionResponse{}
	mi := &file_worldcup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchPredictionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchPredictionResponse) ProtoMessage() {}

func (x *MatchPredictionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worldcup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchPredictionResponse.ProtoReflect.Descriptor instead.
func (*MatchPredictionResponse) Descriptor() ([]byte, []int) {
	return file_worldcup_proto_rawDescGZIP(), []int{1}
}

func (x *MatchPredictionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_worldcup_proto protoreflect.FileDescriptor

const file_worldcup_proto_rawDesc = "" +
	"\n" +
	"\x0eworldcup.proto\x12\fworldcup2026\"\xf4\x01\n" +
	"\x16MatchPredictionRequest\x120\n" +
	"\thome_team\x18\x01 \x01(\x0e2\x13.worldcup2026.TeamsR\bhomeTeam\x120\n" +
	"\taway_team\x18\x02 \x01(\x0e2\x13.worldcup2026.TeamsR\bawayTeam\x12\x1d\n" +
	"\n" +
	"home_goals\x18\x03 \x01(\x05R\thomeGoals\x12\x1d\n" +
	"\n" +
	"away_goals\x18\x04 \x01(\x05R\tawayGoals\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\"1\n" +
	"\x17MatchPredictionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status*G\n" +
	"\x05Teams\x12\x11\n" +
	"\rTEAMS_UNKNOWN\x10\x00\x12\a\n" +
	"\x03GTM\x10\x01\x12\a\n" +
	"\x03MEX\x10\x02\x12\a\n" +
	"\x03BRA\x10\x03\x12\a\n" +
	"\x03ARG\x10\x04\x12\a\n" +
	"\x03ESP\x10\x052w\n" +
	"\x16MatchPredictionService\x12]\n" +
	"\x0eSendPrediction\x12$.worldcup2026.MatchPredictionRequest\x1a%.worldcup2026.MatchPredictionResponseB\x1bZ\x19quiniela/proto/worldcuppbb\x06proto3"

var (
	file_worldcup_proto_rawDescOnce sync.Once
	file_worldcup_proto_rawDescData []byte
)

func file_worldcup_proto_rawDescGZIP() []byte {
	file_worldcup_proto_rawDescOnce.Do(func() {
		file_worldcup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worldcup_proto_rawDesc), len(file_worldcup_proto_rawDesc)))
	})
	return file_worldcup_proto_rawDescData
}

var file_worldcup_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_worldcup_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_worldcup_proto_goTypes = []any{
	(Teams)(0),                      // 0: worldcup2026.Teams
	(*MatchPredictionRequest)(nil),  // 1: worldcup2026.MatchPredictionRequest
	(*MatchPredictionResponse)(nil), // 2: worldcup2026.MatchPredictionResponse
}
var file_worldcup_proto_depIdxs = []int32{
	0, // 0: worldcup2026.MatchPredictionRequest.home_team:type_name -> worldcup2026.Teams
	0, // 1: worldcup2026.MatchPredictionRequest.away_team:type_name -> worldcup2026.Teams
	1, // 2: worldcup2026.MatchPredictionService.SendPrediction:input_type -> worldcup2026.MatchPredictionRequest
	2, // 3: worldcup2026.MatchPredictionService.SendPrediction:output_type -> worldcup2026.MatchPredictionResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_worldcup_proto_init() }
func file_worldcup_proto_init() {
	if File_worldcup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worldcup_proto_rawDesc), len(file_worldcup_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worldcup_proto_goTypes,
		DependencyIndexes: file_worldcup_proto_depIdxs,
		EnumInfos:         file_worldcup_proto_enumTypes,
		MessageInfos:      file_worldcup_proto_msgTypes,
	}.Build()
	File_worldcup_proto = out.File
	file_worldcup_proto_goTypes = nil
	file_worldcup_proto_depIdxs = nil
}
